package com.example.opotracker.ui.common

import java.time.LocalDate

private val FRASES_MOTIVADORAS = listOf(
    "Cada tema que repasas hoy es un paso menos hasta la plaza.",
    "No hace falta ser perfecta, hace falta ser constante.",
    "Un poco cada día pesa más que mucho de vez en cuando.",
    "Hoy no tienes que acabar el temario, solo avanzar un poco más que ayer.",
    "El cansancio de hoy es la plaza de mañana.",
    "Prepararte es un acto de fe en ti misma.",
    "Los repasos de hoy son la seguridad del examen.",
    "No compares tu ritmo con el de nadie más: esta oposición es tuya.",
    "Cada simulacro es un ensayo a tu favor.",
    "Descansar también es parte de estudiar bien.",
    "Vas a llegar, aunque hoy el temario pese.",
    "La constancia gana a la intensidad.",
    "Tu yo del examen te va a agradecer el esfuerzo de hoy.",
    "Un tema resumido hoy es un tema que no vuelve a asustar.",
    "No se trata de saberlo todo, se trata de defenderlo bien.",
    "Cada día que estudias, se acorta la distancia con tu plaza.",
    "Confía en el proceso, aunque hoy no lo sientas.",
    "El examen se prepara en los días normales, no solo en los buenos.",
    "Ir despacio también es avanzar.",
    "Hoy toca sumar un ladrillo más a esa oposición.",
    "Nadie ve las horas de estudio, pero el tribunal sí verá el resultado.",
    "Estudiar cansada un rato es mejor que no estudiar nada.",
    "Cada unidad didáctica que preparas es una menos que improvisar.",
    "El folio en blanco de hoy es el guión seguro de mañana.",
    "No necesitas motivación todos los días, necesitas hábito.",
    "Lo que hoy te cuesta, en el examen se notará que lo dominas.",
    "Un mal día de estudio no borra todos los buenos.",
    "La opositora que fuiste al empezar estaría orgullosa de dónde estás ahora.",
    "Cuenta los temas que ya sabes, no solo los que faltan.",
    "Cada repaso es una capa más de seguridad para el día del examen.",
    "Mereces la plaza tanto como cualquiera que se presente contigo.",
    "El esfuerzo de hoy no se ve, pero se acumula.",
    "No estudies solo para aprobar, estudia para dominarlo.",
    "Cuando dudes de ti, mira todo lo que ya has estudiado.",
    "Preparar oposiciones también es aprender a cuidarte mientras lo haces.",
    "Tu ritmo de hoy no define tu resultado final.",
    "Cada vez que repasas, tu memoria confía un poco más en ti.",
    "La opositora constante llega más lejos que la opositora perfecta.",
    "Un simulacro más es un nervio menos el día del examen.",
    "No dejes que un mal simulacro defina lo que sabes.",
    "Cada tema que personalizas es un tema que suena a ti.",
    "El tribunal no busca perfección, busca criterio y seguridad.",
    "Hoy es un buen día para adelantarte al examen.",
    "Tu constancia de cada día se va a notar en junio.",
    "Estudiar con cariño hacia ti misma también rinde.",
    "Cada objetivo diario cumplido es una victoria pequeña pero real.",
    "No hay atajos, pero sí hay un camino que ya estás recorriendo.",
    "La opositora de éxito no es la que nunca duda, es la que sigue.",
    "Hoy toca cuidar el cuerpo tanto como la cabeza.",
    "Un tema bien estudiado hoy no se va a olvidar mañana.",
    "Cada hora de estudio de hoy es una hora menos de nervios en el examen.",
    "Sé exigente contigo, pero también sé amable.",
    "La regularidad de hoy es la tranquilidad de mañana.",
    "No compites contra el resto, compites contra tu propio ayer.",
    "Este proceso es largo, pero tú también eres constante.",
    "Cada unidad que dominas es una menos que temer en la defensa oral.",
    "El miedo al examen se reduce estudio a estudio.",
    "Hoy puedes ser la versión de ti que sí llega preparada.",
    "Un repaso más siempre suma, nunca resta.",
    "La plaza se construye en los días grises, no solo en los inspirados.",
    "Confía en tu memoria: cada repaso la entrena un poco más.",
    "Estudiar hoy también es un regalo para tu yo de dentro de un año.",
    "No necesitas sentirte lista, necesitas seguir preparándote.",
    "Cada folio que resumes es una idea que ya no se te escapa.",
    "El día del examen solo vas a defender lo que ya sabes: siémbralo ahora.",
    "Tu esfuerzo de hoy no se mide en horas perfectas, se mide en constancia.",
    "Aunque hoy avances poco, sigues yendo hacia delante.",
    "La opositora que se cuida también aprueba.",
    "Cada simulacro de unidad didáctica te acerca a defenderla sin papeles.",
    "No es fracaso parar a descansar, es parte del plan.",
    "Hoy es un buen día para creer un poco más en ti.",
    "El temario se hace pequeño repaso a repaso.",
    "Tu constancia de hoy es la que hablará por ti en el examen.",
    "Aprender a organizarte también es parte de aprobar.",
    "Cada objetivo semanal cumplido te acerca más de lo que crees.",
    "No es lo mismo estudiar con miedo que con determinación: elige la segunda.",
    "Los nervios de hoy se convierten en seguridad si sigues repasando.",
    "Cada día que apareces a estudiar, ya has ganado algo.",
    "Tu plaza no depende de un día perfecto, depende de muchos días normales.",
    "Sigue aunque hoy no tengas ganas: las ganas también se entrenan.",
    "Cuidar tu descanso es cuidar tu memoria.",
    "Cada tema que dominas te acerca a hablar de él sin dudar.",
    "El proceso de oposición también te está haciendo más fuerte.",
    "No hay prisa que valga más que la constancia.",
    "Hoy toca confiar en el trabajo que ya llevas hecho.",
    "La opositora que no se rinde, tarde o temprano, llega.",
    "Cada unidad didáctica lista es una preocupación menos para junio.",
    "Sé paciente contigo: aprender bien lleva tiempo.",
    "El esfuerzo silencioso de hoy también cuenta.",
    "Tu futura yo, con la plaza en la mano, te está esperando.",
    "No busques el momento perfecto para estudiar, busca el momento posible.",
    "Cada repaso es una promesa que le haces a tu memoria.",
    "La disciplina de hoy es libertad el día del examen.",
    "Aunque el temario sea largo, tus repasos también se acumulan.",
    "Hoy puedes sumar un poco más de seguridad a tu oposición.",
    "No hace falta estudiar mucho, hace falta estudiar bien y seguido.",
    "Cada objetivo cumplido hoy es una prueba de que puedes con esto.",
    "El camino a la plaza también se construye en los días difíciles.",
    "Sigue: cada página de hoy es una línea menos que dejar para mañana.",
    "Confía en el proceso, en tu esfuerzo y en ti misma.",
    "Imagina tu clase el día que ya tengas la plaza: eso es lo que estás construyendo hoy.",
    "Dentro de unos meses, este esfuerzo se va a llamar aprobado.",
    "Cuando llegue junio, vas a agradecer cada tarde que hoy dedicas a estudiar.",
    "Recuerda por qué empezaste: por esos niños que aún no conoces.",
    "Tu futura clase ya está esperando a la maestra en la que te estás convirtiendo.",
    "No estudias por obligación, estudias por vocación: no lo olvides en los días duros.",
    "Piensa en el aula, no solo en el examen.",
    "Vas a defender estos temas mejor de lo que crees.",
    "El sorteo de bolas también entrena tus nervios, no solo tu memoria.",
    "Cada simulacro que haces es un ensayo general para el día que de verdad importa.",
    "La opositora del principio no tiene por qué parecerse a la del final: puedes mejorar cada semana.",
    "Cuenta los avances, no los kilómetros que faltan.",
    "No hay temario que no se pueda con constancia diaria.",
    "Cada frase que subrayas hoy es una idea que ya dominas.",
    "Estudiar con orden pesa menos que estudiar con prisa.",
    "El folio en blanco de la programación también se vence, tema a tema.",
    "Aunque hoy el cansancio gane, mañana puedes volver a empezar.",
    "No hace falta tener un buen día para estudiar, solo hace falta empezar.",
    "Cada unidad didáctica que terminas te acerca a hablar de tu aula con seguridad.",
    "La memoria se entrena como un músculo: repite, no fuerces.",
    "Aunque parezca lento, cada semana estás más cerca.",
    "Esta oposición no define tu valor, pero tu esfuerzo sí define tu resultado.",
    "Prepárate para el examen que quieres aprobar, no para el que temes.",
    "El miedo a olvidar se cura repasando, no evitando.",
    "Cada vez que retomas el temario después de un descanso, también es constancia.",
    "Un buen resumen de hoy es un ahorro de tiempo mañana.",
    "Confía en la opositora que ya ha llegado hasta aquí.",
    "No necesitas motivación constante, necesitas un plan que seguir aunque no tengas ganas.",
    "Cada esquema que haces ordena no solo el tema, también tu cabeza.",
    "Tu plaza empieza en la próxima página que estudies.",
    "Aunque el temario sea largo, tu paciencia también lo es.",
    "Estudiar hoy es cuidar a la maestra que serás mañana.",
    "No compares tu progreso de hoy con el de otra opositora: cada camino es distinto.",
    "La disciplina no es dura contigo, te está cuidando.",
    "Cada repaso que haces reduce el margen para los nervios del examen.",
    "El día del examen solo tienes que recordar lo que ya has entendido muchas veces.",
    "Aunque falten meses, cada semana cuenta ya.",
    "La opositora que descansa bien también rinde mejor.",
    "No subestimes lo que ya sabes: es más de lo que crees.",
    "Cada objetivo diario que tachas es una prueba de que puedes con esto.",
    "El esfuerzo de esta semana se va a notar en el próximo simulacro.",
    "Cuando dudes de tu memoria, mira todo lo que ya recuerdas sin esfuerzo.",
    "La plaza no la gana quien más rápido estudia, sino quien no deja de intentarlo.",
    "Cada tema dominado es una conversación menos que temer en la oral.",
    "No hay atajos para dominar un temario, pero sí rutinas que lo hacen más fácil.",
    "Cuídate en el proceso: la opositora agotada también necesita descanso.",
    "Cada vez que estudias cansada y aun así avanzas, te haces más fuerte.",
    "El temario es largo, pero tu memoria es más capaz de lo que imaginas.",
    "Aunque el resultado tarde en llegar, el esfuerzo ya está dando frutos.",
    "La seguridad en el examen se construye repaso a repaso, no de golpe.",
    "No hace falta saberlo todo perfecto, hace falta saberlo defender con calma.",
    "Cada día que estudias es una prueba de que crees en tu propio proyecto.",
    "Tu constancia de hoy también es un ejemplo, aunque nadie la vea.",
    "La opositora paciente avanza más que la que se exige perfección constante.",
    "Recuerda: no estás sola en este proceso, aunque estudies en silencio.",
    "Cada minuto de estudio de hoy es una posibilidad menos de arrepentirte mañana.",
    "No dejes que un simulacro flojo te haga olvidar todo lo que sí sabes.",
    "Estudiar con calma también es avanzar, no solo estudiar rápido.",
    "Cada tema que repasas por tercera vez ya casi es tuyo para siempre.",
    "La plaza se acerca aunque hoy no la sientas cerca.",
    "No hace falta un buen ánimo para sentarte a estudiar, solo hace falta sentarte.",
    "Cada vez que programas tu día de estudio, ya estás un paso por delante.",
    "El esfuerzo de hoy no se pierde, aunque hoy no lo notes.",
    "Confía en el método, incluso en los días en que dudes de ti misma.",
    "Cada unidad didáctica bien preparada es una menos que improvisar en la defensa.",
    "La opositora que se organiza sufre menos que la que estudia sin rumbo.",
    "Aunque el examen todavía quede lejos, cada repaso ya cuenta para ese día.",
    "No necesitas estudiar diez horas, necesitas estudiar todos los días un poco.",
    "Cada vez que terminas un tema, tu temario da menos miedo.",
    "El nerviosismo del examen se reduce con cada simulacro que haces.",
    "Aunque hoy no acabes lo que querías, mañana puedes seguir desde ahí.",
    "La memoria necesita repetición, no perfección.",
    "Cada página que subrayas hoy es una idea menos que se te puede escapar en el examen.",
    "Confía en que tu esfuerzo va a hablar por ti en junio.",
    "No hay mala racha de estudio que no se pueda retomar mañana.",
    "Cada vez que vuelves a un tema difícil, lo entiendes un poco mejor.",
    "La opositora constante no necesita ser la más rápida, solo la que no para.",
    "Aunque el cuerpo esté cansado, la cabeza sigue aprendiendo si tú se lo permites.",
    "Cada simulacro que completas te acerca al día en que ya no tengas miedo al tribunal.",
    "No pienses en todo el temario, piensa solo en el tema de hoy.",
    "La plaza también se prepara cuidando tu descanso y tu ánimo.",
    "Cada objetivo semanal que cumples es una prueba de que el plan funciona.",
    "Confía en tus repasos: están haciendo su trabajo aunque no lo notes al instante.",
    "No dejes que el cansancio de un mal día borre el esfuerzo de toda la semana.",
    "Cada tema que personalizas con tus propias palabras se queda mejor en tu memoria.",
    "La disciplina de hoy es la tranquilidad que sentirás el día del examen.",
    "Aunque parezca que no avanzas, cada repaso deja huella.",
    "Cada vez que te sientas a estudiar aunque no tengas ganas, estás entrenando algo más importante que el temario: la constancia.",
    "No necesitas sentirte preparada del todo, necesitas seguir preparándote cada día.",
    "La opositora de éxito también tiene días malos, solo que no se rinde en ellos.",
    "Cada minuto que dedicas hoy es una inversión en la maestra que serás.",
    "Confía en el camino, aunque hoy no veas la meta.",
    "No hace falta acabar el temario en un día, hace falta no dejarlo nunca del todo.",
    "Cada unidad didáctica que revisas de nuevo se vuelve un poco más tuya.",
    "La memoria confía en la constancia más que en la intensidad.",
    "Aunque hoy el simulacro no salga como esperabas, cada intento suma experiencia.",
    "Cada tema que dominas también te acerca a la maestra que quieres ser.",
    "No subestimes el poder de un repaso corto pero constante.",
    "La plaza se construye con paciencia, no con prisa.",
    "Confía en ti: cada día que estudias demuestras que puedes con esto.",
    "Cada tema que entiendes hoy ya no te lo va a poder quitar nadie.",
    "La plaza se gana con perseverancia, no con suerte.",
    "Hoy es un buen día para acercarte un poco más a tu aula.",
    "No necesitas estudiar perfecto, necesitas estudiar de verdad.",
    "Cada repaso que haces es una duda menos el día del examen.",
    "Confía en que cada pequeño avance también cuenta.",
    "El temario no te pesa a ti, tú le vas ganando terreno a él.",
    "Cada vez que abres los apuntes, ya has hecho lo más difícil: empezar.",
    "Tu esfuerzo de hoy también educa a la maestra que vas a ser.",
    "No hace falta un plan perfecto, hace falta un plan que sigas.",
    "Cada simulacro te acerca un poco más a sentirte cómoda ante el tribunal.",
    "La opositora tranquila estudia mejor que la opositora con prisa.",
    "Cada unidad que preparas hoy es una menos que temer mañana.",
    "Aunque el examen dé respeto, tu preparación también cuenta.",
    "Hoy toca avanzar, no toca ser perfecta.",
    "Cada tema que dominas es una idea menos que se te puede olvidar.",
    "Confía en tu esfuerzo, aunque el resultado tarde en verse.",
    "No dejes que la comparación te robe la motivación de hoy.",
    "Cada objetivo que cumples hoy, por pequeño que sea, también suma.",
    "El folio en blanco también se llena letra a letra.",
    "Aunque hoy cueste arrancar, empezar también es avanzar.",
    "Cada repaso que repites es un paso más hacia la seguridad.",
    "La memoria premia la constancia, no la prisa.",
    "Hoy también estás construyendo la maestra que serás.",
    "No necesitas sentirte con fuerzas para empezar, las fuerzas llegan estudiando.",
    "Cada tema que resumes hoy es tiempo que te ahorras mañana.",
    "Confía en que el esfuerzo de hoy también deja huella.",
    "La plaza no se improvisa el último mes, se construye cada día.",
    "Cada vez que repasas un tema difícil, se vuelve un poco más fácil.",
    "No hace falta ser la más rápida, hace falta no parar.",
    "Hoy puedes elegir avanzar, aunque sea poco.",
    "Cada simulacro que haces también entrena tu calma.",
    "La opositora que cuida su descanso también cuida su memoria.",
    "Aunque el temario asuste al principio, se hace manejable poco a poco.",
    "Cada unidad didáctica que revisas te acerca a defenderla con seguridad.",
    "Confía en que cada esfuerzo silencioso también construye la plaza.",
    "No hace falta acabarlo todo hoy, hace falta no dejarlo del todo.",
    "Cada objetivo que te marcas también te ordena la cabeza.",
    "El examen se prepara con constancia, no con nervios de última hora.",
    "Hoy también puedes sumar seguridad a tu oposición.",
    "Cada vez que te sientas a estudiar, estás eligiendo tu futuro.",
    "La disciplina también se construye con pequeños hábitos diarios.",
    "Aunque no lo sientas, cada repaso te acerca más a la plaza.",
    "Confía en que aprender bien también lleva su tiempo.",
    "No compares tu proceso con el de otra opositora: el tuyo también vale.",
    "Cada tema que estudias hoy también es una idea menos que defender de memoria pura.",
    "La constancia también se nota en los días en los que no tienes ganas.",
    "Hoy también puedes ser un poco más la maestra que quieres ser.",
    "Cada repaso corto también cuenta si lo haces con atención.",
    "Confía en tu criterio: sabes más de lo que crees.",
    "No hace falta tener miedo al temario, hace falta tener un plan.",
    "Cada vez que estudias con calma, tu memoria también lo agradece.",
    "La opositora organizada también duerme mejor.",
    "Aunque el resultado no se vea hoy, el esfuerzo ya está sembrado.",
    "Cada tema que entiendes de verdad ya no necesita tanto repaso.",
    "Confía en que cada simulacro también es un entrenamiento válido.",
    "No necesitas motivación todos los días, necesitas un hábito que sostenga los días malos.",
    "Cada unidad que terminas también te acerca a hablar de tu aula sin miedo.",
    "El esfuerzo de hoy también construye la confianza de mañana.",
    "Cuidar tu cabeza mientras estudias también es parte del plan.",
    "Repasar hoy es una forma de cuidar tu tranquilidad de mañana.",
    "Pasar un tema por completo también cuenta para el resultado final.",
    "No hace falta estudiar con miedo, hace falta estudiar con constancia.",
    "Retomar el temario después de parar también es elegir seguir.",
    "La plaza se construye incluso en los días en los que apenas avanzas.",
    "Aunque hoy no tengas ganas, cinco minutos de estudio también ayudan.",
    "Un tema personalizado con tus palabras se queda mejor en tu cabeza.",
    "También mereces llegar a esa aula que imaginas.",
    "No necesitas ser perfecta ante el tribunal, necesitas ser tú misma con seguridad.",
    "Cada objetivo semanal cumplido también te acerca más de lo que crees.",
    "El miedo se reduce estudiando el temario, no evitándolo.",
    "Un repaso más siempre suma un poco de seguridad.",
    "Dudar y seguir igualmente también es avanzar.",
    "Cada esfuerzo de hoy también tiene su recompensa, aunque tarde en llegar.",
    "No hace falta un día perfecto, hace falta un día honesto contigo misma.",
    "Un simulacro que no sale bien también enseña algo importante.",
    "La opositora también necesita reírse de vez en cuando.",
    "Aunque el temario canse, tú sigues aquí, y eso ya dice mucho.",
    "Dominar un tema también es una preocupación menos para junio.",
    "Estás avanzando aunque hoy no lo notes.",
    "No necesitas comparar tu ritmo con nadie, solo mantener el tuyo.",
    "Un repaso también fortalece la memoria a largo plazo.",
    "El esfuerzo cuenta incluso cuando nadie lo está mirando.",
    "Hoy también es un buen día para creer en tu propio proyecto.",
    "Cada unidad se hace más ligera cuanto más la trabajas.",
    "Los pequeños hábitos diarios también suman a lo grande.",
    "No hace falta tenerlo todo controlado, hace falta seguir intentándolo.",
    "Explicar un tema con tus propias palabras también lo hace tuyo.",
    "La disciplina se entrena igual que la memoria.",
    "Los días flojos también forman parte del camino.",
    "Cumplir un objetivo también es la prueba de que el esfuerzo funciona.",
    "Vas a llegar preparada a ese día, aunque hoy te cueste creerlo.",
    "No necesitas estudiar sin parar, necesitas estudiar sin abandonar.",
    "Cada repaso reduce un poco más el miedo al olvido.",
    "El camino se hace más corto cuando no lo dejas a medias.",
    "Puedes ser constante hoy, aunque sea a tu manera.",
    "Un simulacro más también te entrena para confiar en lo que sabes.",
    "Estás más cerca de lo que sientes ahora mismo.",
    "Cada día que estudias también te acerca a esa aula que imaginas.",
    "Sigue estudiando: cada tema de hoy es un peldaño más hacia tu plaza.",
)

/** Frase estable durante todo el día, cambia cada 24h. */
fun fraseDelDia(): String {
    val diaDelAnio = LocalDate.now().dayOfYear
    return FRASES_MOTIVADORAS[diaDelAnio % FRASES_MOTIVADORAS.size]
}
