package com.example.opotracker.ui.common

import java.time.LocalDate

private val FRASES_MOTIVADORAS = listOf(
    "Cada tema que repasas hoy es un paso menos hasta la plaza.",
    "No hace falta ser perfecta, hace falta ser constante.",
    "Un poco cada día pesa más que mucho de vez en cuando.",
    "Hoy no tienes que acabar el temario, solo avanzar un poco más que ayer.",
    "El cansancio de hoy es la plaza de mañana.",
    "Prepararte es un acto de fe en ti misma.",
    "Los repasos de hoy son la seguridad del examen.",
    "No compares tu ritmo con el de nadie más: esta oposición es tuya.",
    "Cada simulacro es un ensayo a tu favor.",
    "Descansar también es parte de estudiar bien.",
    "Vas a llegar, aunque hoy el temario pese.",
    "La constancia gana a la intensidad.",
    "Tu yo del examen te va a agradecer el esfuerzo de hoy.",
    "Un tema resumido hoy es un tema que no vuelve a asustar.",
    "No se trata de saberlo todo, se trata de defenderlo bien.",
    "Cada día que estudias, se acorta la distancia con tu plaza.",
    "Confía en el proceso, aunque hoy no lo sientas.",
    "El examen se prepara en los días normales, no solo en los buenos.",
    "Ir despacio también es avanzar.",
    "Hoy toca sumar un ladrillo más a esa oposición.",
    "Nadie ve las horas de estudio, pero el tribunal sí verá el resultado.",
    "Estudiar cansada un rato es mejor que no estudiar nada.",
    "Cada unidad didáctica que preparas es una menos que improvisar.",
    "El folio en blanco de hoy es el guión seguro de mañana.",
    "No necesitas motivación todos los días, necesitas hábito.",
    "Lo que hoy te cuesta, en el examen se notará que lo dominas.",
    "Un mal día de estudio no borra todos los buenos.",
    "La opositora de hace un año estaría orgullosa de dónde estás ahora.",
    "Cuenta los temas que ya sabes, no solo los que faltan.",
    "Cada repaso es una capa más de seguridad para el día del examen.",
    "Mereces la plaza tanto como cualquiera que se presente contigo.",
    "El esfuerzo de hoy no se ve, pero se acumula.",
    "No estudies solo para aprobar, estudia para dominarlo.",
    "Cuando dudes de ti, mira todo lo que ya has estudiado.",
    "Preparar oposiciones también es aprender a cuidarte mientras lo haces.",
    "Tu ritmo de hoy no define tu resultado final.",
    "Cada vez que repasas, tu memoria confía un poco más en ti.",
    "La opositora constante llega más lejos que la opositora perfecta.",
    "Un simulacro más es un nervio menos el día del examen.",
    "No dejes que un mal simulacro defina lo que sabes.",
    "Cada tema que personalizas es un tema que suena a ti.",
    "El tribunal no busca perfección, busca criterio y seguridad.",
    "Hoy es un buen día para adelantarte al examen.",
    "Tu constancia de estas semanas se va a notar en junio.",
    "Estudiar con cariño hacia ti misma también rinde.",
    "Cada objetivo diario cumplido es una victoria pequeña pero real.",
    "No hay atajos, pero sí hay un camino que ya estás recorriendo.",
    "La opositora de éxito no es la que nunca duda, es la que sigue.",
    "Hoy toca cuidar el cuerpo tanto como la cabeza.",
    "Un tema bien estudiado hoy no se va a olvidar mañana.",
    "Cada hora de estudio de hoy es una hora menos de nervios en el examen.",
    "Sé exigente contigo, pero también sé amable.",
    "La regularidad de hoy es la tranquilidad de mañana.",
    "No compites contra el resto, compites contra tu propio ayer.",
    "Este proceso es largo, pero tú también eres constante.",
    "Cada unidad que dominas es una menos que temer en la defensa oral.",
    "El miedo al examen se reduce estudio a estudio.",
    "Hoy puedes ser la versión de ti que sí llega preparada.",
    "Un repaso más siempre suma, nunca resta.",
    "La plaza se construye en los días grises, no solo en los inspirados.",
    "Confía en tu memoria: llevas meses entrenándola.",
    "Estudiar hoy también es un regalo para tu yo de dentro de un año.",
    "No necesitas sentirte lista, necesitas seguir preparándote.",
    "Cada folio que resumes es una idea que ya no se te escapa.",
    "El día del examen solo vas a defender lo que ya sabes: siémbralo ahora.",
    "Tu esfuerzo de hoy no se mide en horas perfectas, se mide en constancia.",
    "Aunque hoy avances poco, sigues yendo hacia delante.",
    "La opositora que se cuida también aprueba.",
    "Cada simulacro de unidad didáctica te acerca a defenderla sin papeles.",
    "No es fracaso parar a descansar, es parte del plan.",
    "Hoy es un buen día para creer un poco más en ti.",
    "El temario se hace pequeño repaso a repaso.",
    "Tu constancia de hoy es la que hablará por ti en el examen.",
    "Aprender a organizarte también es parte de aprobar.",
    "Cada objetivo semanal cumplido te acerca más de lo que crees.",
    "No es lo mismo estudiar con miedo que con determinación: elige la segunda.",
    "Los nervios de hoy se convierten en seguridad si sigues repasando.",
    "Cada día que apareces a estudiar, ya has ganado algo.",
    "Tu plaza no depende de un día perfecto, depende de muchos días normales.",
    "Sigue aunque hoy no tengas ganas: las ganas también se entrenan.",
    "Cuidar tu descanso es cuidar tu memoria.",
    "Cada tema que dominas te acerca a hablar de él sin dudar.",
    "El proceso de oposición también te está haciendo más fuerte.",
    "No hay prisa que valga más que la constancia.",
    "Hoy toca confiar en el trabajo que ya llevas hecho.",
    "La opositora que no se rinde, tarde o temprano, llega.",
    "Cada unidad didáctica lista es una preocupación menos para junio.",
    "Sé paciente contigo: aprender bien lleva tiempo.",
    "El esfuerzo silencioso de hoy también cuenta.",
    "Tu futura yo, con la plaza en la mano, te está esperando.",
    "No busques el momento perfecto para estudiar, busca el momento posible.",
    "Cada repaso es una promesa que le haces a tu memoria.",
    "La disciplina de hoy es libertad el día del examen.",
    "Aunque el temario sea largo, tus repasos también se acumulan.",
    "Hoy puedes sumar un poco más de seguridad a tu oposición.",
    "No hace falta estudiar mucho, hace falta estudiar bien y seguido.",
    "Cada objetivo cumplido hoy es una prueba de que puedes con esto.",
    "El camino a la plaza también se construye en los días difíciles.",
    "Sigue: cada página de hoy es una línea menos que dejar para mañana.",
    "Confía en el proceso, en tu esfuerzo y en ti misma.",
)

/** Frase estable durante todo el día, cambia cada 24h. */
fun fraseDelDia(): String {
    val diaDelAnio = LocalDate.now().dayOfYear
    return FRASES_MOTIVADORAS[diaDelAnio % FRASES_MOTIVADORAS.size]
}
